<a href="https://colab.research.google.com/github/alecbidaran/VIT_From_Scratch_Pytorch/blob/main/Torch_VIT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install torch torchvision torchaudio

!pip install torch-snippets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import cv2
import glob
import pandas as pd
import random
from torchvision import transforms,datasets,models
from torch.utils.data import DataLoader, Dataset
from torch_snippets import *

In [ ]:
!pip install -q kaggle
! mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [ ]:
! cp kaggle.json ~/.kaggle/

! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d tongpython/cat-and-dog
!unzip cat-and-dog.zip

Streaming output truncated to the last 5000 lines.
  inflating: training_set/training_set/cats/cat.3704.jpg  
  inflating: training_set/training_set/cats/cat.3705.jpg  
  inflating: training_set/training_set/cats/cat.3706.jpg  
  inflating: training_set/training_set/cats/cat.3707.jpg  
  inflating: training_set/training_set/cats/cat.3708.jpg  
  inflating: training_set/training_set/cats/cat.3709.jpg  
  inflating: training_set/training_set/cats/cat.371.jpg  
  inflating: training_set/training_set/cats/cat.3710.jpg  
  inflating: training_set/training_set/cats/cat.3711.jpg  
  inflating: training_set/training_set/cats/cat.3712.jpg  
  inflating: training_set/training_set/cats/cat.3713.jpg  
  inflating: training_set/training_set/cats/cat.3714.jpg  
  inflating: training_set/training_set/cats/cat.3715.jpg  
  inflating: training_set/training_set/cats/cat.3716.jpg  
  inflating: training_set/training_set/cats/cat.3717.jpg  
  inflating: training_set/training_set/cats/cat.3718.jpg  
  infl

In [ ]:
train_transforms = transforms.Compose([transforms.RandomRotation(30),
                                       transforms.RandomResizedCrop(224),
                                       transforms.RandomHorizontalFlip(),
                                       transforms.ToTensor(),
                                       transforms.Normalize([0.485, 0.456, 0.406],
                                                            [0.229, 0.224, 0.225])])

test_transforms = transforms.Compose([transforms.Resize(255),
                                      transforms.CenterCrop(224),
                                      transforms.ToTensor(),
                                      transforms.Normalize([0.485, 0.456, 0.406],
                                                           [0.229, 0.224, 0.225])])

In [ ]:
train_dataset=datasets.ImageFolder(root="training_set/training_set/",transform=train_transforms)
test_dataset=datasets.ImageFolder(root="/content/test_set/test_set/",transform=test_transforms)

In [ ]:
train_dataloader=torch.utils.data.DataLoader(train_dataset,batch_size=16,shuffle=True)
test_dataloader=torch.utils.data.DataLoader(test_dataset,batch_size=16,shuffle=False)

In [ ]:
img=test_dataset[0][0]
img.shape

torch.Size([3, 224, 224])

In [ ]:
vit=models.vit_b_16(pretrained=True)
vit(img.view(1,3,224,224))

tensor([[-1.2154e+00, -3.9141e-01,  5.7224e-02, -2.1846e-01, -1.2204e-01,
          5.8036e-01, -1.7841e-01, -3.9989e-01,  1.2310e-01, -6.7138e-01,
         -1.1223e+00, -1.1607e-01, -9.2524e-01, -8.6900e-01, -3.4015e-01,
         -7.5285e-01, -4.1219e-01, -6.1369e-01, -5.0552e-02, -4.7335e-01,
         -1.9998e-01, -4.3465e-01, -6.6775e-01, -2.7116e-01, -4.0427e-01,
         -1.9757e-01, -1.9062e-01, -8.0500e-03,  1.2452e-01, -7.4982e-01,
         -5.4842e-01, -3.6861e-01,  7.1192e-01,  3.7120e-01,  7.9694e-02,
         -4.9356e-01,  7.3214e-02, -5.5020e-01, -6.5112e-02,  1.8020e-01,
         -3.3737e-01, -3.4522e-01,  7.0129e-01, -3.2300e-01,  8.6534e-02,
          1.2357e-02, -1.0066e-01, -8.7452e-01, -3.5584e-01,  1.1650e-01,
          2.7849e-02, -1.4312e+00,  9.0147e-01, -1.5506e-01, -1.3750e-01,
         -4.7385e-01, -1.3997e-01, -9.6173e-02, -1.8775e-01, -4.1061e-01,
          6.1560e-01,  1.1634e-01,  3.2239e-01,  6.3931e-01, -4.5128e-01,
         -2.4093e-01, -6.7981e-01,  3.

In [ ]:
for param in vit.parameters():
  param.require_grad=True
print(vit)

VisionTransformer(
  (conv_proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
  (encoder): Encoder(
    (dropout): Dropout(p=0.0, inplace=False)
    (layers): Sequential(
      (encoder_layer_0): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
        )
        (dropout): Dropout(p=0.0, inplace=False)
        (ln_2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (mlp): MLPBlock(
          (linear_1): Linear(in_features=768, out_features=3072, bias=True)
          (act): GELU()
          (dropout_1): Dropout(p=0.0, inplace=False)
          (linear_2): Linear(in_features=3072, out_features=768, bias=True)
          (dropout_2): Dropout(p=0.0, inplace=False)
        )
      )
      (encoder_layer_1): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
 

In [ ]:
vit.heads=torch.nn.Sequential(nn.Linear(768,2))
print(vit)

VisionTransformer(
  (conv_proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
  (encoder): Encoder(
    (dropout): Dropout(p=0.0, inplace=False)
    (layers): Sequential(
      (encoder_layer_0): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
        )
        (dropout): Dropout(p=0.0, inplace=False)
        (ln_2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (mlp): MLPBlock(
          (linear_1): Linear(in_features=768, out_features=3072, bias=True)
          (act): GELU()
          (dropout_1): Dropout(p=0.0, inplace=False)
          (linear_2): Linear(in_features=3072, out_features=768, bias=True)
          (dropout_2): Dropout(p=0.0, inplace=False)
        )
      )
      (encoder_layer_1): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
 

In [ ]:
vit(img.view(1,3,224,224))

tensor([[0.1323, 0.1097]], grad_fn=<AddmmBackward0>)

In [ ]:
model=vit.to("cuda")
optimizer=torch.optim.Adam(model.parameters(),lr=0.001)
loss_fn=torch.nn.CrossEntropyLoss()


In [ ]:
def train_batch(batch):
  data,label=batch
  model.train()
  optimizer.zero_grad()
  pred=model(data.cuda())
  loss=loss_fn(pred,label.cuda())
  acc=(torch.max(pred,1)[1]==label.cuda()).float().mean()
  loss.backward()
  optimizer.step()
  return loss.item(),acc.item()
@torch.no_grad()
def valid_batch(batch):
  data,label=batch
  model.eval()
  pred=model(data.cuda())
  loss=loss_fn(pred,label.cuda())
  acc=(torch.max(pred,1)[1]==label.cuda()).float().mean()
  return loss.item(),acc.item()

In [ ]:
n_epoch=10
log=Report(n_epoch)
for epochs in range(n_epoch):
  N = len(train_dataloader)
  for i,data in enumerate(train_dataloader):
    loss,acc=train_batch(data)
    log.record(epochs+(i+1)/N,trn_loss=loss,trn_acc=acc,end='\r')
  N = len(test_dataloader)
  for i,batch in enumerate(test_dataloader):
    loss,acc=valid_batch(batch)
    log.record(epochs+(i+1)/N,val_loss=loss,val_acc=acc,end='\r')


  log.report_avgs(epochs+1)


EPOCH: 1.000	trn_loss: 0.729	trn_acc: 0.504	val_loss: 0.688	val_acc: 0.549	(353.68s - 3183.16s remaining)
EPOCH: 2.000	trn_loss: 0.690	trn_acc: 0.538	val_loss: 0.695	val_acc: 0.521	(706.41s - 2825.65s remaining)
EPOCH: 3.000	trn_loss: 0.703	trn_acc: 0.529	val_loss: 0.740	val_acc: 0.502	(1059.17s - 2471.40s remaining)
EPOCH: 4.000	trn_loss: 0.695	trn_acc: 0.511	val_loss: 0.688	val_acc: 0.546	(1411.19s - 2116.79s remaining)
EPOCH: 5.000	trn_loss: 0.684	trn_acc: 0.538	val_loss: 0.693	val_acc: 0.501	(1764.00s - 1764.00s remaining)
EPOCH: 6.000	trn_loss: 0.689	trn_acc: 0.539	val_loss: 0.670	val_acc: 0.590	(2115.75s - 1410.50s remaining)
EPOCH: 7.000	trn_loss: 0.679	trn_acc: 0.553	val_loss: 0.676	val_acc: 0.558	(2467.77s - 1057.62s remaining)
EPOCH: 8.000	trn_loss: 0.669	trn_acc: 0.583	val_loss: 0.667	val_acc: 0.603	(2820.57s - 705.14s remaining)
EPOCH: 9.000	trn_loss: 0.665	trn_acc: 0.581	val_loss: 0.647	val_acc: 0.622	(3173.00s - 352.56s remaining)
EPOCH: 10.000	trn_loss: 0.662	trn_acc: 0.

In [ ]:
model.eval()
img,label=test_dataset[-1]
model(img.view(1,3,224,224).cuda())

tensor([[-0.1138,  0.1153]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [ ]:
label

1